sudo: required

notifications:
  email: false
  
language: rust

before_install:
  - sudo apt-get install rake
  - git clone git://github.com/stpettersens/netsh.git
  - cd netsh
  - cargo build --release
  - sudo cp target/release/netsh /usr/bin
  - cd ..
  
script:
  - rake
