[package]
name = "ssid_demo"
version = "0.1.0"
authors = ["Sam Saint-Pettersen <s.stpettersen+github@gmail.com>"]

[dependencies]
ssid = { git = "https://github.com/stpettersens/ssid.git" } 
os_type = "0.6.0"
